// Warframe Grind Dashboard — Weapons Data

const WEAPONS = [
  // ─── EASY ─────────────────────────────────────────────────────
  { name: "Cronus", type: "Melee", category: "Sword", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Boss", location: "Tolstoj, Mercury", boss: "Captain Vor", missionType: "Assassination", notes: "Blueprint guaranteed from Captain Vor on Mercury. Early game, very fast farm.", blueprint: "Vor drop", locked: false, tags: ["early-game", "sword"], wikiUrl: "https://warframe.fandom.com/wiki/Cronus" },
  { name: "Seer", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Tolstoj, Mercury", boss: "Captain Vor", missionType: "Assassination", notes: "All 3 parts drop from Captain Vor on Mercury. Early and consistent.", blueprint: "Vor drop", locked: false, tags: ["early-game", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Seer" },
  { name: "Twin Gremlins", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Exta, Ceres", boss: "Lech Kril & Capt. Vor", missionType: "Assassination", notes: "Blueprint from Exta boss fight (drop table 2). Blueprint from Market too.", blueprint: "Boss drop / Market", locked: false, tags: ["early-game", "dual-pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Twin_Gremlins" },
  { name: "Miter", type: "Primary", category: "Launcher", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Exta, Ceres", boss: "Lech Kril & Capt. Vor", missionType: "Assassination", notes: "Parts from Exta (drop table 2). All parts from same boss. Easy farm.", blueprint: "Boss drop", locked: false, tags: ["saw-launcher", "ceres"], wikiUrl: "https://warframe.fandom.com/wiki/Miter" },
  { name: "Boltor", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from the in-game Market for Credits. Very beginner friendly.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "rifle", "beginner"], wikiUrl: "https://warframe.fandom.com/wiki/Boltor" },
  { name: "Braton", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market for Credits. Starter-level rifle.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "rifle", "beginner"], wikiUrl: "https://warframe.fandom.com/wiki/Braton" },
  { name: "Kunai", type: "Secondary", category: "Thrown", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Starter secondary. Also a login reward.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "thrown"], wikiUrl: "https://warframe.fandom.com/wiki/Kunai" },
  { name: "Hek", type: "Primary", category: "Shotgun", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Strong early-to-mid game shotgun.", blueprint: "Market (credits)", locked: false, tags: ["shotgun", "grineer"], wikiUrl: "https://warframe.fandom.com/wiki/Hek" },
  { name: "Karak", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Reliable mid-game Grineer rifle.", blueprint: "Market (credits)", locked: false, tags: ["rifle", "grineer"], wikiUrl: "https://warframe.fandom.com/wiki/Karak" },
  { name: "Orthos", type: "Melee", category: "Polearm", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Great early polearm.", blueprint: "Market (credits)", locked: false, tags: ["polearm", "early-game"], wikiUrl: "https://warframe.fandom.com/wiki/Orthos" },
  { name: "Skana", type: "Melee", category: "Sword", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Starter", location: "Starting loadout", boss: "N/A", missionType: "Starter / Market", notes: "Given as one of the 3 starter weapons. Also available from Market.", blueprint: "Starter / Market", locked: false, tags: ["starter", "sword"], wikiUrl: "https://warframe.fandom.com/wiki/Skana" },

  // ─── MEDIUM ────────────────────────────────────────────────────
  { name: "Pathocyst", type: "Primary", category: "Launcher", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Boss", location: "Exequias, Deimos", boss: "Zealoid Prelate", missionType: "Assassination", notes: "All 3 parts from Zealoid Prelate on Deimos. Unique Infested launcher. Requires Heart of Deimos progress.", blueprint: "Zealoid Prelate drop", locked: false, tags: ["deimos", "infested", "launcher"], wikiUrl: "https://warframe.fandom.com/wiki/Pathocyst" },
  { name: "Broken War", type: "Melee", category: "Sword", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The Second Dream / The War Within", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded from The Second Dream quest. One of the best early swords. Cannot be traded. Lost if sold without The War progression.", blueprint: "Quest reward", locked: true, tags: ["quest-reward", "sword", "shadow-stalker"], wikiUrl: "https://warframe.fandom.com/wiki/Broken_War" },
  { name: "Skiajati", type: "Melee", category: "Nikana", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The Sacrifice Quest", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded from The Sacrifice quest. MR 9+ required. Unique invisibility on finisher. If sold, must redo The Sacrifice which can't be replayed.", blueprint: "The Sacrifice reward", locked: true, tags: ["quest-reward", "nikana", "umbra"], wikiUrl: "https://warframe.fandom.com/wiki/Skiajati" },
  { name: "Paracesis", type: "Melee", category: "Heavy Blade", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Quest", location: "The Sacrifice Quest", boss: "N/A", missionType: "Quest Reward + Crafting", notes: "Blueprint from The Sacrifice. Requires Nitain Extract + Sentient cores. Sentient Anomaly node for Cores. The only weapon that can damage Sentient resistances from the start.", blueprint: "The Sacrifice reward", locked: true, tags: ["quest-reward", "sentient", "heavy-blade"], wikiUrl: "https://warframe.fandom.com/wiki/Paracesis" },
  { name: "Nataruk", type: "Primary", category: "Bow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The New War Quest", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded at end of The New War quest. Exceptionally powerful bow. Cannot be obtained again from quest — if sold, must buy for plat or trade.", blueprint: "New War quest reward", locked: true, tags: ["quest-reward", "bow", "sentient"], wikiUrl: "https://warframe.fandom.com/wiki/Nataruk" },
  { name: "Cedo", type: "Primary", category: "Shotgun", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Dojo Research", location: "Bio Lab, Clan Dojo", boss: "N/A", missionType: "Dojo Research", notes: "Blueprint from Bio Lab in Clan Dojo. Requires rare Deimos resources for crafting (Thaumica, Mytocardia Spore). One of the best status shotguns.", blueprint: "Bio Lab – Dojo", locked: false, tags: ["dojo", "shotgun", "status"], wikiUrl: "https://warframe.fandom.com/wiki/Cedo" },
  { name: "Zarr", type: "Primary", category: "Launcher", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Dojo Research", location: "Chem Lab, Clan Dojo", boss: "N/A", missionType: "Dojo Research", notes: "Blueprint from Chem Lab in Clan Dojo. Great AoE cannon.", blueprint: "Chem Lab – Dojo", locked: false, tags: ["dojo", "launcher", "aoe"], wikiUrl: "https://warframe.fandom.com/wiki/Zarr" },
  { name: "Ignis Wraith", type: "Primary", category: "Rifle", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Special", location: "Clan Dojo / Trade", boss: "N/A", missionType: "Clan Research / Trading", notes: "Blueprint from a Clan Dojo that researched it during Operation: Tubemen of Regor. Trade with other players if your clan lacks it. Very popular fire weapon.", blueprint: "Clan (event research) / Trade", locked: false, tags: ["clan-event", "flamethrower", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Ignis_Wraith" },
  { name: "Zenith", type: "Primary", category: "Rifle", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 300)", notes: "Rewarded at Day 300 login milestone. Unique alt-fire mode that places auto-target turret. Time-gated by login streak — cannot be obtained any other way.", blueprint: "Day 300 Login Reward", locked: true, tags: ["login-reward", "unique", "time-gated"], wikiUrl: "https://warframe.fandom.com/wiki/Zenith" },
  { name: "Stug", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Corpus blob pistol. Blueprint from Market.", blueprint: "Market (credits)", locked: false, tags: ["corpus", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Stug" },
  { name: "Furis", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. The auto-pistol you get with Warframe starter pack.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Furis" },
  { name: "Arca Plasmor", type: "Primary", category: "Shotgun", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Syndicate", location: "Arbiters of Hexis / Red Veil", boss: "N/A", missionType: "Syndicate Offering", notes: "Bought from Arbiters of Hexis or Red Veil syndicate at max rank for 20,000 standing. Requires Rank 5 (Exalted).", blueprint: "Syndicate offering", locked: false, tags: ["syndicate", "shotgun", "void-damage"], wikiUrl: "https://warframe.fandom.com/wiki/Arca_Plasmor" },
  { name: "Catchmoon", type: "Secondary", category: "Kitgun", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna / Cetus", boss: "N/A", missionType: "Kitgun Crafting", notes: "Assembled from Kitgun parts: Catchmoon chamber + any grip + any loader. Buy parts from Legs in Fortuna. Requires Solaris United standing.", blueprint: "Legs – Fortuna (Kitgun parts)", locked: false, tags: ["kitgun", "fortuna", "secondary"], wikiUrl: "https://warframe.fandom.com/wiki/Catchmoon" },
  { name: "Glaive", type: "Melee", category: "Glaive", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Iconic thrown melee disc. Good utility on Glaive-type builds.", blueprint: "Market (credits)", locked: false, tags: ["glaive", "thrown"], wikiUrl: "https://warframe.fandom.com/wiki/Glaive" },
  { name: "Redeemer", type: "Melee", category: "Gunblade", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Gunblade blueprint from Market. Unique combo mechanic.", blueprint: "Market (credits)", locked: false, tags: ["gunblade", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Redeemer" },

  // ─── HARD ──────────────────────────────────────────────────────
  { name: "Kuva Bramma", type: "Primary", category: "Bow", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Random chance to spawn from Kuva Lich. Farm murmurs across Grineer missions. Need to complete The War Within first. RNG on weapon type per Lich.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "bow", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Bramma" },
  { name: "Kuva Nukor", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Random type per Lich spawn. Extremely powerful secondary — Kuva Nukor variant is top meta. Complete The War Within first. Farm murmurs on Grineer nodes.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "pistol", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Nukor" },
  { name: "Kuva Zarr", type: "Primary", category: "Launcher", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Spawn a Lich wielding Zarr via Grineer missions. High AoE damage. Requires War Within + murmur grind.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "launcher", "aoe"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Zarr" },
  { name: "Tenet Arca Plasmor", type: "Primary", category: "Shotgun", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Sister of Parvos System", boss: "Sister of Parvos", missionType: "Nemesis (Sister)", notes: "Random Sister weapon type. Requires Call of the Tempestarii quest + Granum Void entry. Strong Void-damage shotgun variant.", blueprint: "Sister of Parvos vanquish/convert", locked: false, tags: ["tenet", "nemesis", "shotgun", "void-damage"], wikiUrl: "https://warframe.fandom.com/wiki/Tenet_Arca_Plasmor" },
  { name: "Tenet Cycron", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Sister of Parvos System", boss: "Sister of Parvos", missionType: "Nemesis (Sister)", notes: "Random Sister weapon. Requires Call of the Tempestarii + Granum Void. Powerful beam pistol with viral.", blueprint: "Sister of Parvos vanquish/convert", locked: false, tags: ["tenet", "nemesis", "beam-pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Tenet_Cycron" },
  { name: "Felarx", type: "Primary", category: "Shotgun", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", notes: "Requires Duviri Paradox quest completion then farming Incarnon Genesis adapter via The Circuit (Steel Path). Weekly gated by Circuit rotations.", boss: "N/A", missionType: "Duviri Circuit (Weekly)", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "shotgun", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Felarx" },
  { name: "Phenmor", type: "Primary", category: "Rifle", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", boss: "N/A", missionType: "Duviri Circuit (Weekly)", notes: "Incarnon weapon from Duviri Circuit. Weekly-gated rotations. Need Duviri Paradox completed.", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "rifle", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Phenmor" },
  { name: "Laetum", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", boss: "N/A", missionType: "Duviri Circuit (Weekly)", notes: "Top-tier Incarnon pistol. Duviri Circuit weekly. Requires Duviri Paradox completion.", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "pistol", "meta", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Laetum" },
  { name: "Praedos", type: "Melee", category: "Tonfas", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Duviri – Acrithis Shop", boss: "N/A", missionType: "Duviri", notes: "Buy blueprint from Acrithis in Duviri using Pathos Clamps and Duviri resources. No RNG but requires running Duviri content.", blueprint: "Acrithis – Duviri", locked: false, tags: ["duviri", "tonfas"], wikiUrl: "https://warframe.fandom.com/wiki/Praedos" },
  { name: "Verdilac", type: "Melee", category: "Whip", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Duviri – Acrithis Shop", boss: "N/A", missionType: "Duviri", notes: "Buy from Acrithis in Duviri with Pathos Clamps.", blueprint: "Acrithis – Duviri", locked: false, tags: ["duviri", "whip"], wikiUrl: "https://warframe.fandom.com/wiki/Verdilac" },
  { name: "Sporothrix", type: "Primary", category: "Sniper", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "Son – Token system", missionType: "Token Vendor", notes: "Buy from Son in Necralisk with Son Tokens earned from conservation (Deimos animals). Requires grinding Son standing + tokens.", blueprint: "Son – Necralisk (tokens)", locked: false, tags: ["deimos", "conservation", "sniper"], wikiUrl: "https://warframe.fandom.com/wiki/Sporothrix" },
  { name: "Bubonico", type: "Primary", category: "Launcher", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "Son – Token system", missionType: "Token Vendor", notes: "Son Token vendor in Necralisk. Conservation + Deimos standing required.", blueprint: "Son – Necralisk (tokens)", locked: false, tags: ["deimos", "conservation", "launcher"], wikiUrl: "https://warframe.fandom.com/wiki/Bubonico" },
  { name: "Cortege", type: "Primary", category: "Rifle", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Bounty", location: "Zariman / Holdfasts", boss: "N/A", missionType: "Holdfasts Bounty", notes: "Parts from Holdfasts bounties on Zariman. Requires Angels of the Zariman quest.", blueprint: "Holdfasts Bounty – Zariman", locked: false, tags: ["zariman", "bounty", "void"], wikiUrl: "https://warframe.fandom.com/wiki/Cortege" },
  { name: "Gaze", type: "Secondary", category: "Kitgun", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna", boss: "N/A", missionType: "Kitgun Crafting", notes: "Gaze chamber Kitgun. Buy from Legs in Fortuna with Solaris United standing.", blueprint: "Legs – Fortuna (Kitgun parts)", locked: false, tags: ["kitgun", "fortuna", "beam"], wikiUrl: "https://warframe.fandom.com/wiki/Gaze" },

  // ─── NIGHTMARE ─────────────────────────────────────────────────
  { name: "Mutalist Quanta", type: "Primary", category: "Rifle", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Eris Invasion Alerts", boss: "N/A", missionType: "Invasion (Infested)", notes: "Blueprint ONLY from specific Infested Invasion alerts. Appears rarely. You must watch the Alerts tab. If you miss it, wait for the next rotation. Very time-gated.", blueprint: "Invasion Alert (Infested)", locked: true, tags: ["alert-only", "invasion", "time-gated", "rare"], wikiUrl: "https://warframe.fandom.com/wiki/Mutalist_Quanta" },
  { name: "Prisma Gorgon", type: "Primary", category: "Rifle", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Baro Ki'Teer (Void Trader)", boss: "N/A", missionType: "Void Trader (Bi-weekly)", notes: "ONLY sold by Baro Ki'Teer when he visits a Relay every 2 weeks. Costs Ducats + Credits. Very limited availability — miss the window and wait 2 more weeks.", blueprint: "Baro Ki'Teer (Ducats + Credits)", locked: true, tags: ["baro", "void-trader", "time-gated", "ducats"], wikiUrl: "https://warframe.fandom.com/wiki/Prisma_Gorgon" },
  { name: "Prisma Skana", type: "Melee", category: "Sword", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Baro Ki'Teer (Void Trader)", boss: "N/A", missionType: "Void Trader (Bi-weekly)", notes: "Only from Baro Ki'Teer during his visits. Limited Ducats + Credits cost. Rotates irregularly — can be months between appearances.", blueprint: "Baro Ki'Teer", locked: true, tags: ["baro", "void-trader", "time-gated"], wikiUrl: "https://warframe.fandom.com/wiki/Prisma_Skana" },
  { name: "Azima", type: "Secondary", category: "Pistol", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 100)", notes: "Rewarded only at Day 100 of login milestones. Cannot be earned any other way without trading. If sold, must trade or wait years for another login cycle.", blueprint: "Day 100 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Azima" },
  { name: "Zylok", type: "Secondary", category: "Pistol", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 200)", notes: "Rewarded only at Day 200 login milestone. No other acquisition method.", blueprint: "Day 200 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Zylok" },
  { name: "Sigma & Octantis", type: "Melee", category: "Sword & Shield", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 600)", notes: "Day 600 login milestone ONLY. The longest grind for any weapon in the game if playing daily.", blueprint: "Day 600 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique", "endgame"], wikiUrl: "https://warframe.fandom.com/wiki/Sigma_%26_Octantis" },
];
