// Warframe Grind Dashboard — Frames Data
// difficulty: Easy / Medium / Hard / Nightmare
// grindScore: 1-10 (10 = worst grind)
// locked: true = hard/impossible to recover if sold
// primeStatus: "active" | "vaulted" | "resurgence" | "noprime"
// primeName: name of the prime version if it exists

const FRAMES = [
  // ─── EASY (Standard boss kills, quick farms) ───────────────────────────────
  {
    name: "Excalibur",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 1,
    method: "Boss",
    location: "War, Mars",
    boss: "Lt. Lech Kril",
    missionType: "Assassination",
    notes: "Starter frame. Very fast boss, low MR required. Blueprint from Market.",
    blueprint: "Market (free)",
    tags: ["starter", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Excalibur"
  },
  {
    name: "Mag",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 1,
    method: "Boss",
    location: "Iliad, Phobos",
    boss: "The Sergeant",
    missionType: "Assassination",
    notes: "Starter frame. Easiest boss in game. Blueprint from Market.",
    blueprint: "Market (free)",
    tags: ["starter", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Mag"
  },
  {
    name: "Volt",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Starter frame. Requires access to a Clan Dojo Tenno Lab. Ask in Recruit chat if you have no clan.",
    blueprint: "Tenno Lab Dojo",
    tags: ["starter", "dojo", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Volt"
  },
  {
    name: "Rhino",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Fossa, Venus",
    boss: "Jackal",
    missionType: "Assassination",
    notes: "Very beginner friendly. Blueprint from Market. Jackal is straightforward.",
    blueprint: "Market (free)",
    tags: ["early-game", "tank"],
    wikiUrl: "https://warframe.fandom.com/wiki/Rhino"
  },
  {
    name: "Ember",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Tethys, Saturn",
    boss: "General Sargas Ruk",
    missionType: "Assassination",
    notes: "Blueprint from Market. Boss is straightforward, mid-game planet.",
    blueprint: "Market (free)",
    tags: ["dps", "mid-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Ember"
  },
  {
    name: "Frost",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Exta, Ceres",
    boss: "Lt. Lech Kril & Capt. Vor",
    missionType: "Assassination",
    notes: "Blueprint from Market. Dual-boss fight but still manageable early.",
    blueprint: "Market (free)",
    tags: ["defense", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Frost"
  },
  {
    name: "Banshee",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo access. No RNG after research is complete.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo"],
    wikiUrl: "https://warframe.fandom.com/wiki/Banshee"
  },
  {
    name: "Nekros",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Magnacidium, Deimos",
    boss: "Lephantis",
    missionType: "Assassination",
    notes: "Blueprint from Market. Lephantis is a classic boss. Unlock Deimos first.",
    blueprint: "Market (free)",
    tags: ["loot-frame", "support"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nekros"
  },
  {
    name: "Nezha",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo", "utility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nezha"
  },
  {
    name: "Wukong",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo"],
    wikiUrl: "https://warframe.fandom.com/wiki/Wukong"
  },
  {
    name: "Zephyr",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo", "mobility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Zephyr"
  },
  {
    name: "Valkyr",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Themisto, Jupiter",
    boss: "Alad V",
    missionType: "Assassination",
    notes: "Blueprint from Market. Alad V is easy. Requires completing Jupiter Junction.",
    blueprint: "Market (free)",
    tags: ["melee", "tank"],
    wikiUrl: "https://warframe.fandom.com/wiki/Valkyr"
  },
  {
    name: "Nova",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Naamah, Europa",
    boss: "Raptors",
    missionType: "Assassination",
    notes: "Blueprint from Market. Raptors are very farmable. Use F key to drop them.",
    blueprint: "Market (free)",
    tags: ["nuke", "dps"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nova"
  },
  {
    name: "Loki",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Psamathe, Neptune",
    boss: "Hyena Pack",
    missionType: "Assassination",
    notes: "Blueprint from Market. Hyena Pack is fast. Good for stealth players.",
    blueprint: "Market (free)",
    tags: ["stealth", "utility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Loki"
  },
  {
    name: "Hydroid",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Oro, Earth",
    boss: "Councilor Vay Hek",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires MR5 to unlock Oro. Vay Hek has a tricky phase but is manageable.",
    blueprint: "Market (free)",
    tags: ["loot-frame", "water"],
    wikiUrl: "https://warframe.fandom.com/wiki/Hydroid"
  },
  {
    name: "Oberon",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Special",
    location: "Empyrean Proxima Missions",
    boss: "Points of Interest",
    missionType: "Empyrean",
    notes: "Blueprint from Market. Parts from Empyrean Points of Interest in various Proximas. Play Railjack and they'll come naturally.",
    blueprint: "Market (free)",
    tags: ["support", "hybrid"],
    wikiUrl: "https://warframe.fandom.com/wiki/Oberon"
  },
  {
    name: "Lavos",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Bounty",
    location: "Necralisk, Deimos",
    boss: "Father (Entrati)",
    missionType: "Standing Vendor",
    notes: "Buy blueprints from Father in the Necralisk with Entrati standing. Straightforward once Deimos is unlocked.",
    blueprint: "Father – Necralisk",
    tags: ["deimos", "alchemist"],
    wikiUrl: "https://warframe.fandom.com/wiki/Lavos"
  },
  {
    name: "Nyx",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Various (Invasion)",
    boss: "Phorid",
    missionType: "Assassination (Invasion)",
    notes: "Blueprint from Market. Phorid spawns during Infestation invasions. Check the Alerts/Invasions tab.",
    blueprint: "Market (free)",
    tags: ["cc", "psychic"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nyx"
  },
  {
    name: "Vauban",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Nightwave",
    location: "Nightwave Cred Offerings",
    boss: "N/A",
    missionType: "Nightwave",
    notes: "Buy from Nightwave Cred Offerings for 25 creds each part (75 total). Systems can also be bought from Market.",
    blueprint: "Nightwave / Market",
    tags: ["cc", "trap", "nightwave"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Vauban"
  },

  // ─── MEDIUM ───────────────────────────────────────────────────────────────
  {
    name: "Trinity",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Hades, Pluto",
    boss: "Ambulas",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires 20 Animo Nav Beacons per run — farm from Corpus Tilesets (Animo Beacons from defeating Oxium Osprey-like units). Hard-ish gating.",
    blueprint: "Market (free)",
    tags: ["healer", "support", "late-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Trinity"
  },
  {
    name: "Saryn",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Merrow, Sedna",
    boss: "Kela De Thaym",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires 25 Judgement Points. Farm JPs from Rathuum (Nakki/Yam/Vodyanoi). Good Endo along the way.",
    blueprint: "Market (free)",
    tags: ["nuke", "dps", "meta"],
    wikiUrl: "https://warframe.fandom.com/wiki/Saryn"
  },
  {
    name: "Atlas",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Eris",
    boss: "Jordas Golem",
    missionType: "Assassination",
    notes: "All 4 BPs from Jordas Golem. Requires completing The Jordas Precept quest first. Boss requires Archwing.",
    blueprint: "Jordas Golem drop",
    tags: ["melee", "brawler"],
    wikiUrl: "https://warframe.fandom.com/wiki/Atlas"
  },
  {
    name: "Wisp",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Ganymede, Jupiter",
    boss: "The Ropalolyst",
    missionType: "Assassination",
    notes: "All 4 BPs from Ropalolyst. Requires Chimera Prologue completion. Boss has unique mechanics but is learnable.",
    blueprint: "Ropalolyst drop",
    tags: ["support", "buff", "meta"],
    wikiUrl: "https://warframe.fandom.com/wiki/Wisp"
  },
  {
    name: "Equinox",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Titania, Uranus",
    boss: "Tyl Regor",
    missionType: "Assassination",
    notes: "Blueprint from Market. UNIQUE CRAFT: Must build Night Aspect AND Day Aspect (6 components total) before the main frame. Takes ~1 week craft time. Tyl Regor is also an annoying underwater fight.",
    blueprint: "Market (free)",
    tags: ["unique-craft", "dual-aspect", "utility"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Equinox"
  },
  {
    name: "Chroma",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Quest",
    location: "Junction Rewards",
    boss: "N/A",
    missionType: "Junction + Quest",
    notes: "Blueprint from The New Strange quest. Parts from Uranus/Neptune/Pluto Junctions. REQUIRES: already-built Frost, Ember, Volt, and Saryn components as crafting mats.",
    blueprint: "The New Strange Quest",
    tags: ["quest", "elemental", "dragon"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Chroma"
  },
  {
    name: "Mesa",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 5,
    method: "Boss",
    location: "Eris (Mutalist Nav Key)",
    boss: "Mutalist Alad V",
    missionType: "Assassination (Key-gated)",
    notes: "Requires crafting a Mutalist Alad V Assassinate Key using Nav Coordinates from Infested Invasions. Blueprint from Patient Zero quest. Extra gating steps but boss is doable.",
    blueprint: "Patient Zero Quest",
    tags: ["gunslinger", "dps", "key-gated"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Mesa"
  },
  {
    name: "Gara",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Plains of Eidolon",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Saya's Vigil quest. Parts from PoE Bounties (Lv 5-15 Chassis, Lv 10-30 Systems, Lv 20-40 Neuroptics). Requires PoE resource crafting.",
    blueprint: "Saya's Vigil Quest",
    tags: ["quest", "poe", "glass"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gara"
  },
  {
    name: "Garuda",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Orb Vallis (Fortuna)",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Vox Solaris quest. Parts from Orb Vallis Bounties. Requires Toroids and Fortuna resources for crafting — extra time investment.",
    blueprint: "Vox Solaris Quest",
    tags: ["quest", "fortuna", "gore"],
    wikiUrl: "https://warframe.fandom.com/wiki/Garuda"
  },
  {
    name: "Revenant",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Plains of Eidolon (Lv 40-60)",
    boss: "Eidolon-adjacent",
    missionType: "Bounty + Quest",
    notes: "Blueprint from Mask of the Revenant quest. Parts from PoE lv 40-60 Bounties. Requires Eidolon-adjacent game knowledge. Specific bounty tiers can be slow.",
    blueprint: "Mask of the Revenant Quest",
    tags: ["quest", "poe", "eidolon"],
    wikiUrl: "https://warframe.fandom.com/wiki/Revenant"
  },
  {
    name: "Titania",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "The Silver Grove",
    boss: "N/A",
    missionType: "Quest",
    notes: "All BPs from The Silver Grove quest missions. Requires scanning specific rare plants — bring Synthesis Scanner. Quest takes ~2–3 days craft time.",
    blueprint: "Silver Grove Quest",
    tags: ["quest", "fairy", "archwing"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Titania"
  },
  {
    name: "Inaros",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Sands of Inaros Quest",
    boss: "Quest bosses",
    missionType: "Quest",
    notes: "Quest blueprint bought from Baro Ki'Teer (Prime Access vendor — only appears periodically). Final stage can spawn Manics which are annoying. All BPs from quest.",
    blueprint: "Baro Ki'Teer (50 Ducats + 25k Credits)",
    tags: ["quest", "tank", "egypt"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Inaros"
  },
  {
    name: "Octavia",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Quest",
    location: "Various + Lua",
    boss: "Music puzzle (Lua)",
    missionType: "Quest + Survival + Cache Hunt",
    notes: "Blueprint from Octavia's Anthem quest. Chassis from music puzzle on Lua (unique!). Systems from Cache hunt on Lua. Neuroptics from Deimos Survival (Terrorem, Rot C). Spread across the star chart.",
    blueprint: "Octavia's Anthem Quest",
    tags: ["quest", "music", "dps"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Octavia"
  },
  {
    name: "Hildryn",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Orb Vallis (Exploiter Orb)",
    boss: "Exploiter Orb",
    missionType: "Boss Fight (Special)",
    notes: "Blueprint from Little Duck (Vox Solaris Rank: Agent). Parts from Exploiter Orb drops in Orb Vallis. Requires Fortuna rank progression + Lazulite Toroids. Very doable with a squad.",
    blueprint: "Little Duck – Vox Solaris",
    tags: ["fortuna", "shield-tank", "vox-solaris"],
    wikiUrl: "https://warframe.fandom.com/wiki/Hildryn"
  },
  {
    name: "Baruuk",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 5,
    method: "Bounty",
    location: "Fortuna / Orb Vallis",
    boss: "N/A",
    missionType: "Standing + Crafting",
    notes: "All BPs from Little Duck (Vox Solaris standing: Rank 2 & 3). Crafting requires 8 unique resources including Toroids and rare Vallis resources. Time-gated by daily standing.",
    blueprint: "Little Duck – Vox Solaris Rank 2/3",
    tags: ["fortuna", "melee", "standing-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Baruuk"
  },
  {
    name: "Protea",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Special",
    location: "Granum Void (Corpus Ship)",
    boss: "Granum Void",
    missionType: "Granum Void (Timed)",
    notes: "All BPs from Granum Void encounters in Corpus Ship missions. Requires Granum Crowns (from Treasurer enemy). Different parts need different Granum Void tiers.",
    blueprint: "Granum Void runs",
    tags: ["support", "engineer", "unique-mechanic"],
    wikiUrl: "https://warframe.fandom.com/wiki/Protea"
  },
  {
    name: "Yareli",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Dojo / K-Drive",
    boss: "K-Drive (Ventkids)",
    missionType: "Dojo Research + Quest",
    notes: "Blueprint from The Waverider Quest (requires K-Drive). Components from Ventkid's Bash Labs in Dojo. Requires Dojo access.",
    blueprint: "Dojo – Ventkid's Bash Lab",
    tags: ["quest", "k-drive", "water"],
    wikiUrl: "https://warframe.fandom.com/wiki/Yareli"
  },
  {
    name: "Dante",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Disruption",
    location: "Armatus, Deimos",
    boss: "N/A",
    missionType: "Disruption (Rotation C)",
    notes: "All BPs from Disruption on Armatus, Deimos at Rotation C. Needs Whispers in the Walls quest content unlocked.",
    blueprint: "Disruption – Armatus, Deimos",
    tags: ["deimos", "disruption", "support"],
    wikiUrl: "https://warframe.fandom.com/wiki/Dante"
  },
  {
    name: "Gyre",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Chrysalith, Zariman",
    boss: "N/A",
    missionType: "Holdfasts Bounties",
    notes: "All BPs from Holdfasts Bounties on the Zariman. Different parts at different bounty tiers. Requires Angels of the Zariman quest.",
    blueprint: "Holdfasts Bounties – Chrysalith",
    tags: ["zariman", "electric", "bounty"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gyre"
  },
  {
    name: "Qorvex",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Sanctum Anatomica",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Whispers in the Walls quest. Parts from Sanctum Anatomica Bounties at various tiers. Need Whispers in the Walls completion.",
    blueprint: "Whispers in the Walls Quest",
    tags: ["deimos", "bounty", "radiation"],
    wikiUrl: "https://warframe.fandom.com/wiki/Qorvex"
  },
  {
    name: "Xaku",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Cambion Drift, Deimos",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Heart of Deimos quest. Parts from Cambion Drift Bounties at various levels. Requires Deimos resources for crafting (Thaumica, Mytocardia Spore, etc.).",
    blueprint: "Heart of Deimos Quest",
    tags: ["deimos", "void", "bounty"],
    wikiUrl: "https://warframe.fandom.com/wiki/Xaku"
  },
  {
    name: "Styanax",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Special",
    location: "Kahl-175's Garrison",
    boss: "N/A",
    missionType: "Break Narmer Missions",
    notes: "Parts and BPs from Chipper at Kahl's Garrison using Garrison Stocks. Earn Stocks by completing Break Narmer weekly challenges. Limited by weekly challenges.",
    blueprint: "Chipper – Kahl's Garrison",
    tags: ["garrison", "support", "time-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Styanax"
  },
  {
    name: "Kullervo",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Special",
    location: "Duviri, The Circuit",
    boss: "N/A",
    missionType: "Duviri – Acrithis Shop",
    notes: "All BPs purchased from Acrithis in Duviri using Undercroft Essence and Duviri resources. No RNG — pure grinding Duviri content.",
    blueprint: "Acrithis – Duviri",
    tags: ["duviri", "melee", "curse"],
    wikiUrl: "https://warframe.fandom.com/wiki/Kullervo"
  },
  {
    name: "Limbo",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "The Limbo Theorem Quest",
    boss: "N/A",
    missionType: "Quest (Archwing required)",
    notes: "Neuroptics and Chassis from The Limbo Theorem quest. Systems from Market. Requires Archwing. Components must be built one at a time (~5 days total craft).",
    blueprint: "Limbo Theorem Quest",
    tags: ["quest", "time-gated", "cc"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Limbo"
  },
  {
    name: "Mirage",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Hidden Messages Quest",
    boss: "N/A",
    missionType: "Quest (Riddles)",
    notes: "Neuroptics and Chassis from Hidden Messages quest missions. Systems from Market. Riddles can be cryptic — use wiki for clues. Sequential craft gates (~4-5 days).",
    blueprint: "Hidden Messages Quest",
    tags: ["quest", "trickster", "dps"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Mirage"
  },
  {
    name: "Ivara",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Spy",
    location: "Spy Missions (Various)",
    boss: "N/A",
    missionType: "Spy (Rotation C)",
    notes: "All parts from Spy missions at Rotation C. Neuroptics from Spy Tier 1, Chassis from Spy Tier 2, Systems from Spy Tier 3 (or Lua Spy). RNG + requires flawless Spy skill.",
    blueprint: "Spy Missions – Rotation C",
    tags: ["spy", "stealth", "support"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Ivara"
  },

  // ─── HARD ──────────────────────────────────────────────────────────────────
  {
    name: "Khora",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Sanctuary Onslaught",
    location: "Sanctuary Onslaught",
    boss: "N/A",
    missionType: "Sanctuary Onslaught",
    notes: "All BPs from Normal Sanctuary Onslaught (not Elite). Rotation C every 8 waves (~30 min). Very low individual drop rates. Expect dozens of runs. Also available from Duviri Circuit.",
    blueprint: "Sanctuary Onslaught – Rotation C",
    tags: ["so", "loot-frame", "rng-nightmare"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Khora"
  },
  {
    name: "Nidus",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Infested Salvage",
    location: "Oestrus, Eris",
    boss: "N/A",
    missionType: "Infested Salvage (Rotation C)",
    notes: "Blueprint from The Glast Gambit quest. Parts from Rotation C of Infested Salvage on Oestrus, Eris. ~20 min per rotation C. Almost never played → usually solo. Brutal.",
    blueprint: "The Glast Gambit Quest",
    tags: ["infested", "hard-farm", "scaling"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Nidus"
  },
  {
    name: "Harrow",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Special",
    location: "Multiple Sources",
    boss: "Various",
    missionType: "Spy + Defection + Void Fissure",
    notes: "Blueprint: Chains of Harrow quest. Chassis: Void Fissure enemies. Neuroptics: Spy Rotation A on Pago (Kuva Fortress) or Rotation C. Systems: Defection missions (Tier 2/3, Rotation B/C) — the most hated mission type. Spread across 3 different hard grinds.",
    blueprint: "Chains of Harrow Quest",
    tags: ["quest", "defection", "support", "priest"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Harrow"
  },
  {
    name: "Gauss",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Disruption",
    location: "Kappa, Sedna / Kelpie, Sedna",
    boss: "N/A",
    missionType: "Disruption (Rotation C)",
    notes: "Systems from Market. Parts from Tier C Disruption on Kelpie, Sedna. Each component ~7.84% drop per Rotation C. RNG heavy. Requires finishing most of the star chart.",
    blueprint: "Market (free)",
    tags: ["disruption", "speed", "rng-heavy"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gauss"
  },
  {
    name: "Ash",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Void Storm",
    location: "Proxima Regions (Empyrean)",
    boss: "Manic Enemies",
    missionType: "Empyrean / Void Storm",
    notes: "Parts from different Proxima regions via Defense/Survival/Exterminate/Volatile missions. Neuroptics: Neptune Proxima; Chassis: Pluto Proxima; Systems: Venus Proxima. Requires Railjack. Parts drop from Manic enemies — rare spawns in Kuva Survival too.",
    blueprint: "Market (free)",
    tags: ["railjack", "proxima", "ninja"],
    wikiUrl: "https://warframe.fandom.com/wiki/Ash"
  },
  {
    name: "Sevagoth",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Void Storm",
    location: "Pluto / Neptune / Veil Proxima",
    boss: "N/A",
    missionType: "Void Storm (Empyrean)",
    notes: "Blueprint from Call of the Tempestarii quest. Parts from Void Storms in Pluto Proxima, Neptune Proxima, and Veil Proxima. Requires Railjack. Low drop rates per run.",
    blueprint: "Call of the Tempestarii Quest",
    tags: ["railjack", "void-storm", "shadow"],
    wikiUrl: "https://warframe.fandom.com/wiki/Sevagoth"
  },
  {
    name: "Dagath",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Dojo Research",
    location: "Dagath's Hollow, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "All BPs from Dagath's Hollow in Clan Dojo. Requires the Dojo room to be built first. Then farm rare resources (Vents Horn from Kuva survival, Rune Marrow, etc.) for crafting.",
    blueprint: "Dagath's Hollow – Dojo",
    tags: ["dojo", "spooky", "curse"],
    wikiUrl: "https://warframe.fandom.com/wiki/Dagath"
  },
  {
    name: "Citrine",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Special",
    location: "Mirror Defense, Mars",
    boss: "N/A",
    missionType: "Mirror Defense (Rotation C)",
    notes: "All parts from Rotation C of Mirror Defense on Mars. Very slow rotation — rounds take 6–8 min each. Low individual drop rates. Time-restricted mission type. Considered one of the worst farms currently.",
    blueprint: "Mirror Defense – Mars Rot C",
    tags: ["mirror-defense", "time-restricted", "crystal"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Citrine"
  },
  {
    name: "Voruna",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Special",
    location: "Yuvarium, Lua",
    boss: "Lua Thrax",
    missionType: "Survival (Rotation C)",
    notes: "All parts from Rotation C of Survival on Yuvarium, Lua. Requires ~20 min per Rotation C run. Needs Lua Thrax resources for crafting (450 Lua Thrax total). Unlock Lua via The War Within quest.",
    blueprint: "Survival – Yuvarium, Lua",
    tags: ["lua", "survival", "four-headed"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Voruna"
  },
  {
    name: "Caliban",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Bounty",
    location: "Narmer Bounties",
    boss: "N/A",
    missionType: "Narmer Bounty",
    notes: "Parts from Narmer Bounties in Fortuna/Cetus (post New War). Systems from Market. RNG-heavy bounty drops. Crafting requires 12+ unique resources across open worlds.",
    blueprint: "Narmer Bounties",
    tags: ["new-war", "bounty", "sentient"],
    wikiUrl: "https://warframe.fandom.com/wiki/Caliban"
  },

  // ─── MORE HARD FRAMES ─────────────────────────────────────────────────────
  {
    name: "Jade",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Brutus, Uranus (Ascension)",
    boss: "Sister of Parvos (Ascension)",
    missionType: "Ascension Mode",
    notes: "Blueprint from Jade Shadows quest (requires The New War). Parts from Ascension mission on Brutus, Uranus — 5% drop rate each. Pity system via Vestigial Motes (buy from Ordis at Drifter Camp). Needs 450 Motes per part via pity shop.",
    blueprint: "Jade Shadows Quest",
    tags: ["quest", "ascension", "support", "angel"],
    wikiUrl: "https://warframe.fandom.com/wiki/Jade"
  },
  {
    name: "Koumei",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Special",
    location: "Saya's Vision, Earth",
    boss: "Infested Oni",
    missionType: "Defense (Weekly)",
    notes: "Requires completing Saya's Vigil and the main weekly Codex quest. Run Saya's Vision on Earth. Includes pity system with Fate Pearls. Weekly time-gated if relying on pity.",
    blueprint: "Saya's Vision Mission",
    tags: ["defense", "weekly", "dice", "rng-gimmick"],
    wikiUrl: "https://warframe.fandom.com/wiki/Koumei"
  },
  {
    name: "Cyte-09",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Bounty",
    location: "Halcyon Mall, Warframe 1999",
    boss: "N/A",
    missionType: "1999 Bounties + Vendor",
    notes: "Blueprint from The Hex quest. Components from 1999 Bounties and purchasable from Amir (1999 Mall vendor) with 1999 standing. Requires full star chart + Duviri Paradox + Lotus Eaters + The Hex.",
    blueprint: "The Hex Quest",
    tags: ["1999", "the-hex", "gunslinger", "standing-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Cyte-09"
  },
  {
    name: "Temple",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Halcyon Mall, Warframe 1999",
    boss: "N/A",
    missionType: "1999 Vendor (Flare)",
    notes: "Parts purchasable from Flare (vendor in Halcyon Mall bar area) with 1999 standing/resources. Requires The Hex quest completion. Also drops from 1999 missions.",
    blueprint: "Flare – Halcyon Mall",
    tags: ["1999", "the-hex", "fire", "exalted"],
    wikiUrl: "https://warframe.fandom.com/wiki/Temple"
  },
  {
    name: "Oraxia",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Isle Weaver, Duviri",
    boss: "Oraxia's Lair",
    missionType: "Duviri – Isle Weaver",
    notes: "Farm from Isle Weaver node in Duviri. Requires The Hex quest + Duviri Paradox + Lotus Eaters. Parts drop from missions with pity system via Husk currency from Domino vendor in Drifter Camp.",
    blueprint: "Isle Weaver – Duviri",
    tags: ["duviri", "the-hex", "spider", "invisibility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Oraxia"
  },

  // ─── NIGHTMARE ────────────────────────────────────────────────────────────
  {
    name: "Grendel",
    difficulty: "Nightmare",
    diffScore: 4,
    grindScore: 9,
    method: "Special",
    location: "Europa (Locator missions)",
    boss: "N/A",
    missionType: "No-Mod Missions (3 types)",
    notes: "Blueprint from Market. Parts require Locators (25 Vitus Essence each = 75 total from Arbitration Honors). Then run 3 special Europa missions — Survival, Defense, Excavation — with ALL MODS DISABLED. No Focus, no Operator. Solo/premade only. Enemies Lv 25–30 but your gear feels naked.",
    blueprint: "Market (free)",
    tags: ["arbitration", "no-mods", "hardest"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Grendel"
  },

  // ─── SHADOWGRAPHER UPDATE (March 25, 2026) ────────────────────────────────
  {
    name: "Follie",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Special",
    location: "Vesper Relay, Venus",
    boss: "Follie (Hunt Mode)",
    missionType: "Follie's Hunt",
    notes: "Requires completing Chains of Harrow first. Head to the ruined Vesper Relay on Venus — enter the inky portal. Collect paint to fill canvases while Follie actively hunts you (instant kill aura). Each run ~4-5 min. Parts drop at 5% per run from Rotation A, OR buy with Atramentum currency from Aspirant Zorba at any Relay (400 Atramentum per part, 1200 total for main BP). Full pity set = 2,400 Atramentum. Highly recommend 4-player squad — runs are faster splitting up to collect paint. Steel Path gives better Atramentum yields.",
    blueprint: "Aspirant Zorba – Relay (1200 Atramentum) OR Follie's Hunt drop (5%)",
    locked: false,
    tags: ["shadowgrapher", "hunt-mode", "ink", "atramentum", "newest"],
    wikiUrl: "https://warframe.fandom.com/wiki/Follie"
  },
];
