// Warframe Grind Dashboard — Complete Frame Data
// Difficulty: 1=Easy, 2=Medium, 3=Hard, 4=Nightmare
// grindScore: 1–10 overall grind rating (10 = worst)

const FRAMES = [
  // ─── EASY (Standard boss kills, quick farms) ───────────────────────────────
  {
    name: "Excalibur",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 1,
    method: "Boss",
    location: "War, Mars",
    boss: "Lt. Lech Kril",
    missionType: "Assassination",
    notes: "Starter frame. Very fast boss, low MR required. Blueprint from Market.",
    blueprint: "Market (free)",
    tags: ["starter", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Excalibur"
  },
  {
    name: "Mag",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 1,
    method: "Boss",
    location: "Iliad, Phobos",
    boss: "The Sergeant",
    missionType: "Assassination",
    notes: "Starter frame. Easiest boss in game. Blueprint from Market.",
    blueprint: "Market (free)",
    tags: ["starter", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Mag"
  },
  {
    name: "Volt",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Starter frame. Requires access to a Clan Dojo Tenno Lab. Ask in Recruit chat if you have no clan.",
    blueprint: "Tenno Lab Dojo",
    tags: ["starter", "dojo", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Volt"
  },
  {
    name: "Rhino",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Fossa, Venus",
    boss: "Jackal",
    missionType: "Assassination",
    notes: "Very beginner friendly. Blueprint from Market. Jackal is straightforward.",
    blueprint: "Market (free)",
    tags: ["early-game", "tank"],
    wikiUrl: "https://warframe.fandom.com/wiki/Rhino"
  },
  {
    name: "Ember",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Tethys, Saturn",
    boss: "General Sargas Ruk",
    missionType: "Assassination",
    notes: "Blueprint from Market. Boss is straightforward, mid-game planet.",
    blueprint: "Market (free)",
    tags: ["dps", "mid-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Ember"
  },
  {
    name: "Frost",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Exta, Ceres",
    boss: "Lt. Lech Kril & Capt. Vor",
    missionType: "Assassination",
    notes: "Blueprint from Market. Dual-boss fight but still manageable early.",
    blueprint: "Market (free)",
    tags: ["defense", "early-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Frost"
  },
  {
    name: "Banshee",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo access. No RNG after research is complete.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo"],
    wikiUrl: "https://warframe.fandom.com/wiki/Banshee"
  },
  {
    name: "Nekros",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Magnacidium, Deimos",
    boss: "Lephantis",
    missionType: "Assassination",
    notes: "Blueprint from Market. Lephantis is a classic boss. Unlock Deimos first.",
    blueprint: "Market (free)",
    tags: ["loot-frame", "support"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nekros"
  },
  {
    name: "Nezha",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo", "utility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nezha"
  },
  {
    name: "Wukong",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo"],
    wikiUrl: "https://warframe.fandom.com/wiki/Wukong"
  },
  {
    name: "Zephyr",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Dojo Research",
    location: "Tenno Lab, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "Requires Clan Dojo Tenno Lab access.",
    blueprint: "Tenno Lab Dojo",
    tags: ["dojo", "mobility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Zephyr"
  },
  {
    name: "Valkyr",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Themisto, Jupiter",
    boss: "Alad V",
    missionType: "Assassination",
    notes: "Blueprint from Market. Alad V is easy. Requires completing Jupiter Junction.",
    blueprint: "Market (free)",
    tags: ["melee", "tank"],
    wikiUrl: "https://warframe.fandom.com/wiki/Valkyr"
  },
  {
    name: "Nova",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Naamah, Europa",
    boss: "Raptors",
    missionType: "Assassination",
    notes: "Blueprint from Market. Raptors are very farmable. Use F key to drop them.",
    blueprint: "Market (free)",
    tags: ["nuke", "dps"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nova"
  },
  {
    name: "Loki",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Psamathe, Neptune",
    boss: "Hyena Pack",
    missionType: "Assassination",
    notes: "Blueprint from Market. Hyena Pack is fast. Good for stealth players.",
    blueprint: "Market (free)",
    tags: ["stealth", "utility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Loki"
  },
  {
    name: "Hydroid",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Oro, Earth",
    boss: "Councilor Vay Hek",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires MR5 to unlock Oro. Vay Hek has a tricky phase but is manageable.",
    blueprint: "Market (free)",
    tags: ["loot-frame", "water"],
    wikiUrl: "https://warframe.fandom.com/wiki/Hydroid"
  },
  {
    name: "Oberon",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Special",
    location: "Empyrean Proxima Missions",
    boss: "Points of Interest",
    missionType: "Empyrean",
    notes: "Blueprint from Market. Parts from Empyrean Points of Interest in various Proximas. Play Railjack and they'll come naturally.",
    blueprint: "Market (free)",
    tags: ["support", "hybrid"],
    wikiUrl: "https://warframe.fandom.com/wiki/Oberon"
  },
  {
    name: "Lavos",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Bounty",
    location: "Necralisk, Deimos",
    boss: "Father (Entrati)",
    missionType: "Standing Vendor",
    notes: "Buy blueprints from Father in the Necralisk with Entrati standing. Straightforward once Deimos is unlocked.",
    blueprint: "Father – Necralisk",
    tags: ["deimos", "alchemist"],
    wikiUrl: "https://warframe.fandom.com/wiki/Lavos"
  },
  {
    name: "Nyx",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Boss",
    location: "Various (Invasion)",
    boss: "Phorid",
    missionType: "Assassination (Invasion)",
    notes: "Blueprint from Market. Phorid spawns during Infestation invasions. Check the Alerts/Invasions tab.",
    blueprint: "Market (free)",
    tags: ["cc", "psychic"],
    wikiUrl: "https://warframe.fandom.com/wiki/Nyx"
  },
  {
    name: "Vauban",
    difficulty: "Easy",
    diffScore: 1,
    grindScore: 2,
    method: "Nightwave",
    location: "Nightwave Cred Offerings",
    boss: "N/A",
    missionType: "Nightwave",
    notes: "Buy from Nightwave Cred Offerings for 25 creds each part (75 total). Systems can also be bought from Market.",
    blueprint: "Nightwave / Market",
    tags: ["cc", "trap", "nightwave"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Vauban"
  },

  // ─── MEDIUM ───────────────────────────────────────────────────────────────
  {
    name: "Trinity",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Hades, Pluto",
    boss: "Ambulas",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires 20 Animo Nav Beacons per run — farm from Corpus Tilesets (Animo Beacons from defeating Oxium Osprey-like units). Hard-ish gating.",
    blueprint: "Market (free)",
    tags: ["healer", "support", "late-game"],
    wikiUrl: "https://warframe.fandom.com/wiki/Trinity"
  },
  {
    name: "Saryn",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Merrow, Sedna",
    boss: "Kela De Thaym",
    missionType: "Assassination",
    notes: "Blueprint from Market. Requires 25 Judgement Points. Farm JPs from Rathuum (Nakki/Yam/Vodyanoi). Good Endo along the way.",
    blueprint: "Market (free)",
    tags: ["nuke", "dps", "meta"],
    wikiUrl: "https://warframe.fandom.com/wiki/Saryn"
  },
  {
    name: "Atlas",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Eris",
    boss: "Jordas Golem",
    missionType: "Assassination",
    notes: "All 4 BPs from Jordas Golem. Requires completing The Jordas Precept quest first. Boss requires Archwing.",
    blueprint: "Jordas Golem drop",
    tags: ["melee", "brawler"],
    wikiUrl: "https://warframe.fandom.com/wiki/Atlas"
  },
  {
    name: "Wisp",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Boss",
    location: "Ganymede, Jupiter",
    boss: "The Ropalolyst",
    missionType: "Assassination",
    notes: "All 4 BPs from Ropalolyst. Requires Chimera Prologue completion. Boss has unique mechanics but is learnable.",
    blueprint: "Ropalolyst drop",
    tags: ["support", "buff", "meta"],
    wikiUrl: "https://warframe.fandom.com/wiki/Wisp"
  },
  {
    name: "Equinox",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Titania, Uranus",
    boss: "Tyl Regor",
    missionType: "Assassination",
    notes: "Blueprint from Market. UNIQUE CRAFT: Must build Night Aspect AND Day Aspect (6 components total) before the main frame. Takes ~1 week craft time. Tyl Regor is also an annoying underwater fight.",
    blueprint: "Market (free)",
    tags: ["unique-craft", "dual-aspect", "utility"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Equinox"
  },
  {
    name: "Chroma",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Quest",
    location: "Junction Rewards",
    boss: "N/A",
    missionType: "Junction + Quest",
    notes: "Blueprint from The New Strange quest. Parts from Uranus/Neptune/Pluto Junctions. REQUIRES: already-built Frost, Ember, Volt, and Saryn components as crafting mats.",
    blueprint: "The New Strange Quest",
    tags: ["quest", "elemental", "dragon"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Chroma"
  },
  {
    name: "Mesa",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 5,
    method: "Boss",
    location: "Eris (Mutalist Nav Key)",
    boss: "Mutalist Alad V",
    missionType: "Assassination (Key-gated)",
    notes: "Requires crafting a Mutalist Alad V Assassinate Key using Nav Coordinates from Infested Invasions. Blueprint from Patient Zero quest. Extra gating steps but boss is doable.",
    blueprint: "Patient Zero Quest",
    tags: ["gunslinger", "dps", "key-gated"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Mesa"
  },
  {
    name: "Gara",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Plains of Eidolon",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Saya's Vigil quest. Parts from PoE Bounties (Lv 5-15 Chassis, Lv 10-30 Systems, Lv 20-40 Neuroptics). Requires PoE resource crafting.",
    blueprint: "Saya's Vigil Quest",
    tags: ["quest", "poe", "glass"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gara"
  },
  {
    name: "Garuda",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Orb Vallis (Fortuna)",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Vox Solaris quest. Parts from Orb Vallis Bounties. Requires Toroids and Fortuna resources for crafting — extra time investment.",
    blueprint: "Vox Solaris Quest",
    tags: ["quest", "fortuna", "gore"],
    wikiUrl: "https://warframe.fandom.com/wiki/Garuda"
  },
  {
    name: "Revenant",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Plains of Eidolon (Lv 40-60)",
    boss: "Eidolon-adjacent",
    missionType: "Bounty + Quest",
    notes: "Blueprint from Mask of the Revenant quest. Parts from PoE lv 40-60 Bounties. Requires Eidolon-adjacent game knowledge. Specific bounty tiers can be slow.",
    blueprint: "Mask of the Revenant Quest",
    tags: ["quest", "poe", "eidolon"],
    wikiUrl: "https://warframe.fandom.com/wiki/Revenant"
  },
  {
    name: "Titania",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "The Silver Grove",
    boss: "N/A",
    missionType: "Quest",
    notes: "All BPs from The Silver Grove quest missions. Requires scanning specific rare plants — bring Synthesis Scanner. Quest takes ~2–3 days craft time.",
    blueprint: "Silver Grove Quest",
    tags: ["quest", "fairy", "archwing"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Titania"
  },
  {
    name: "Inaros",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Sands of Inaros Quest",
    boss: "Quest bosses",
    missionType: "Quest",
    notes: "Quest blueprint bought from Baro Ki'Teer (Prime Access vendor — only appears periodically). Final stage can spawn Manics which are annoying. All BPs from quest.",
    blueprint: "Baro Ki'Teer (50 Ducats + 25k Credits)",
    tags: ["quest", "tank", "egypt"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Inaros"
  },
  {
    name: "Octavia",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Quest",
    location: "Various + Lua",
    boss: "Music puzzle (Lua)",
    missionType: "Quest + Survival + Cache Hunt",
    notes: "Blueprint from Octavia's Anthem quest. Chassis from music puzzle on Lua (unique!). Systems from Cache hunt on Lua. Neuroptics from Deimos Survival (Terrorem, Rot C). Spread across the star chart.",
    blueprint: "Octavia's Anthem Quest",
    tags: ["quest", "music", "dps"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Octavia"
  },
  {
    name: "Hildryn",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Boss",
    location: "Orb Vallis (Exploiter Orb)",
    boss: "Exploiter Orb",
    missionType: "Boss Fight (Special)",
    notes: "Blueprint from Little Duck (Vox Solaris Rank: Agent). Parts from Exploiter Orb drops in Orb Vallis. Requires Fortuna rank progression + Lazulite Toroids. Very doable with a squad.",
    blueprint: "Little Duck – Vox Solaris",
    tags: ["fortuna", "shield-tank", "vox-solaris"],
    wikiUrl: "https://warframe.fandom.com/wiki/Hildryn"
  },
  {
    name: "Baruuk",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 5,
    method: "Bounty",
    location: "Fortuna / Orb Vallis",
    boss: "N/A",
    missionType: "Standing + Crafting",
    notes: "All BPs from Little Duck (Vox Solaris standing: Rank 2 & 3). Crafting requires 8 unique resources including Toroids and rare Vallis resources. Time-gated by daily standing.",
    blueprint: "Little Duck – Vox Solaris Rank 2/3",
    tags: ["fortuna", "melee", "standing-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Baruuk"
  },
  {
    name: "Protea",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Special",
    location: "Granum Void (Corpus Ship)",
    boss: "Granum Void",
    missionType: "Granum Void (Timed)",
    notes: "All BPs from Granum Void encounters in Corpus Ship missions. Requires Granum Crowns (from Treasurer enemy). Different parts need different Granum Void tiers.",
    blueprint: "Granum Void runs",
    tags: ["support", "engineer", "unique-mechanic"],
    wikiUrl: "https://warframe.fandom.com/wiki/Protea"
  },
  {
    name: "Yareli",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Dojo / K-Drive",
    boss: "K-Drive (Ventkids)",
    missionType: "Dojo Research + Quest",
    notes: "Blueprint from The Waverider Quest (requires K-Drive). Components from Ventkid's Bash Labs in Dojo. Requires Dojo access.",
    blueprint: "Dojo – Ventkid's Bash Lab",
    tags: ["quest", "k-drive", "water"],
    wikiUrl: "https://warframe.fandom.com/wiki/Yareli"
  },
  {
    name: "Dante",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Disruption",
    location: "Armatus, Deimos",
    boss: "N/A",
    missionType: "Disruption (Rotation C)",
    notes: "All BPs from Disruption on Armatus, Deimos at Rotation C. Needs Whispers in the Walls quest content unlocked.",
    blueprint: "Disruption – Armatus, Deimos",
    tags: ["deimos", "disruption", "support"],
    wikiUrl: "https://warframe.fandom.com/wiki/Dante"
  },
  {
    name: "Gyre",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Chrysalith, Zariman",
    boss: "N/A",
    missionType: "Holdfasts Bounties",
    notes: "All BPs from Holdfasts Bounties on the Zariman. Different parts at different bounty tiers. Requires Angels of the Zariman quest.",
    blueprint: "Holdfasts Bounties – Chrysalith",
    tags: ["zariman", "electric", "bounty"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gyre"
  },
  {
    name: "Qorvex",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Bounty",
    location: "Sanctum Anatomica",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Whispers in the Walls quest. Parts from Sanctum Anatomica Bounties at various tiers. Need Whispers in the Walls completion.",
    blueprint: "Whispers in the Walls Quest",
    tags: ["deimos", "bounty", "radiation"],
    wikiUrl: "https://warframe.fandom.com/wiki/Qorvex"
  },
  {
    name: "Xaku",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Bounty",
    location: "Cambion Drift, Deimos",
    boss: "N/A",
    missionType: "Bounty",
    notes: "Blueprint from Heart of Deimos quest. Parts from Cambion Drift Bounties at various levels. Requires Deimos resources for crafting (Thaumica, Mytocardia Spore, etc.).",
    blueprint: "Heart of Deimos Quest",
    tags: ["deimos", "void", "bounty"],
    wikiUrl: "https://warframe.fandom.com/wiki/Xaku"
  },
  {
    name: "Styanax",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Special",
    location: "Kahl-175's Garrison",
    boss: "N/A",
    missionType: "Break Narmer Missions",
    notes: "Parts and BPs from Chipper at Kahl's Garrison using Garrison Stocks. Earn Stocks by completing Break Narmer weekly challenges. Limited by weekly challenges.",
    blueprint: "Chipper – Kahl's Garrison",
    tags: ["garrison", "support", "time-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Styanax"
  },
  {
    name: "Kullervo",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Special",
    location: "Duviri, The Circuit",
    boss: "N/A",
    missionType: "Duviri – Acrithis Shop",
    notes: "All BPs purchased from Acrithis in Duviri using Undercroft Essence and Duviri resources. No RNG — pure grinding Duviri content.",
    blueprint: "Acrithis – Duviri",
    tags: ["duviri", "melee", "curse"],
    wikiUrl: "https://warframe.fandom.com/wiki/Kullervo"
  },
  {
    name: "Limbo",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "The Limbo Theorem Quest",
    boss: "N/A",
    missionType: "Quest (Archwing required)",
    notes: "Neuroptics and Chassis from The Limbo Theorem quest. Systems from Market. Requires Archwing. Components must be built one at a time (~5 days total craft).",
    blueprint: "Limbo Theorem Quest",
    tags: ["quest", "time-gated", "cc"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Limbo"
  },
  {
    name: "Mirage",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 3,
    method: "Quest",
    location: "Hidden Messages Quest",
    boss: "N/A",
    missionType: "Quest (Riddles)",
    notes: "Neuroptics and Chassis from Hidden Messages quest missions. Systems from Market. Riddles can be cryptic — use wiki for clues. Sequential craft gates (~4-5 days).",
    blueprint: "Hidden Messages Quest",
    tags: ["quest", "trickster", "dps"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Mirage"
  },
  {
    name: "Ivara",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Spy",
    location: "Spy Missions (Various)",
    boss: "N/A",
    missionType: "Spy (Rotation C)",
    notes: "All parts from Spy missions at Rotation C. Neuroptics from Spy Tier 1, Chassis from Spy Tier 2, Systems from Spy Tier 3 (or Lua Spy). RNG + requires flawless Spy skill.",
    blueprint: "Spy Missions – Rotation C",
    tags: ["spy", "stealth", "support"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Ivara"
  },

  // ─── HARD ──────────────────────────────────────────────────────────────────
  {
    name: "Khora",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Sanctuary Onslaught",
    location: "Sanctuary Onslaught",
    boss: "N/A",
    missionType: "Sanctuary Onslaught",
    notes: "All BPs from Normal Sanctuary Onslaught (not Elite). Rotation C every 8 waves (~30 min). Very low individual drop rates. Expect dozens of runs. Also available from Duviri Circuit.",
    blueprint: "Sanctuary Onslaught – Rotation C",
    tags: ["so", "loot-frame", "rng-nightmare"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Khora"
  },
  {
    name: "Nidus",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Infested Salvage",
    location: "Oestrus, Eris",
    boss: "N/A",
    missionType: "Infested Salvage (Rotation C)",
    notes: "Blueprint from The Glast Gambit quest. Parts from Rotation C of Infested Salvage on Oestrus, Eris. ~20 min per rotation C. Almost never played → usually solo. Brutal.",
    blueprint: "The Glast Gambit Quest",
    tags: ["infested", "hard-farm", "scaling"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Nidus"
  },
  {
    name: "Harrow",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Special",
    location: "Multiple Sources",
    boss: "Various",
    missionType: "Spy + Defection + Void Fissure",
    notes: "Blueprint: Chains of Harrow quest. Chassis: Void Fissure enemies. Neuroptics: Spy Rotation A on Pago (Kuva Fortress) or Rotation C. Systems: Defection missions (Tier 2/3, Rotation B/C) — the most hated mission type. Spread across 3 different hard grinds.",
    blueprint: "Chains of Harrow Quest",
    tags: ["quest", "defection", "support", "priest"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Harrow"
  },
  {
    name: "Gauss",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Disruption",
    location: "Kappa, Sedna / Kelpie, Sedna",
    boss: "N/A",
    missionType: "Disruption (Rotation C)",
    notes: "Systems from Market. Parts from Tier C Disruption on Kelpie, Sedna. Each component ~7.84% drop per Rotation C. RNG heavy. Requires finishing most of the star chart.",
    blueprint: "Market (free)",
    tags: ["disruption", "speed", "rng-heavy"],
    wikiUrl: "https://warframe.fandom.com/wiki/Gauss"
  },
  {
    name: "Ash",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Void Storm",
    location: "Proxima Regions (Empyrean)",
    boss: "Manic Enemies",
    missionType: "Empyrean / Void Storm",
    notes: "Parts from different Proxima regions via Defense/Survival/Exterminate/Volatile missions. Neuroptics: Neptune Proxima; Chassis: Pluto Proxima; Systems: Venus Proxima. Requires Railjack. Parts drop from Manic enemies — rare spawns in Kuva Survival too.",
    blueprint: "Market (free)",
    tags: ["railjack", "proxima", "ninja"],
    wikiUrl: "https://warframe.fandom.com/wiki/Ash"
  },
  {
    name: "Sevagoth",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Void Storm",
    location: "Pluto / Neptune / Veil Proxima",
    boss: "N/A",
    missionType: "Void Storm (Empyrean)",
    notes: "Blueprint from Call of the Tempestarii quest. Parts from Void Storms in Pluto Proxima, Neptune Proxima, and Veil Proxima. Requires Railjack. Low drop rates per run.",
    blueprint: "Call of the Tempestarii Quest",
    tags: ["railjack", "void-storm", "shadow"],
    wikiUrl: "https://warframe.fandom.com/wiki/Sevagoth"
  },
  {
    name: "Dagath",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Dojo Research",
    location: "Dagath's Hollow, Clan Dojo",
    boss: "N/A",
    missionType: "Dojo Research",
    notes: "All BPs from Dagath's Hollow in Clan Dojo. Requires the Dojo room to be built first. Then farm rare resources (Vents Horn from Kuva survival, Rune Marrow, etc.) for crafting.",
    blueprint: "Dagath's Hollow – Dojo",
    tags: ["dojo", "spooky", "curse"],
    wikiUrl: "https://warframe.fandom.com/wiki/Dagath"
  },
  {
    name: "Citrine",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 7,
    method: "Special",
    location: "Mirror Defense, Mars",
    boss: "N/A",
    missionType: "Mirror Defense (Rotation C)",
    notes: "All parts from Rotation C of Mirror Defense on Mars. Very slow rotation — rounds take 6–8 min each. Low individual drop rates. Time-restricted mission type. Considered one of the worst farms currently.",
    blueprint: "Mirror Defense – Mars Rot C",
    tags: ["mirror-defense", "time-restricted", "crystal"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Citrine"
  },
  {
    name: "Voruna",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 6,
    method: "Special",
    location: "Yuvarium, Lua",
    boss: "Lua Thrax",
    missionType: "Survival (Rotation C)",
    notes: "All parts from Rotation C of Survival on Yuvarium, Lua. Requires ~20 min per Rotation C run. Needs Lua Thrax resources for crafting (450 Lua Thrax total). Unlock Lua via The War Within quest.",
    blueprint: "Survival – Yuvarium, Lua",
    tags: ["lua", "survival", "four-headed"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Voruna"
  },
  {
    name: "Caliban",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Bounty",
    location: "Narmer Bounties",
    boss: "N/A",
    missionType: "Narmer Bounty",
    notes: "Parts from Narmer Bounties in Fortuna/Cetus (post New War). Systems from Market. RNG-heavy bounty drops. Crafting requires 12+ unique resources across open worlds.",
    blueprint: "Narmer Bounties",
    tags: ["new-war", "bounty", "sentient"],
    wikiUrl: "https://warframe.fandom.com/wiki/Caliban"
  },

  // ─── MORE HARD FRAMES ─────────────────────────────────────────────────────
  {
    name: "Jade",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Brutus, Uranus (Ascension)",
    boss: "Sister of Parvos (Ascension)",
    missionType: "Ascension Mode",
    notes: "Blueprint from Jade Shadows quest (requires The New War). Parts from Ascension mission on Brutus, Uranus — 5% drop rate each. Pity system via Vestigial Motes (buy from Ordis at Drifter Camp). Needs 450 Motes per part via pity shop.",
    blueprint: "Jade Shadows Quest",
    tags: ["quest", "ascension", "support", "angel"],
    wikiUrl: "https://warframe.fandom.com/wiki/Jade"
  },
  {
    name: "Koumei",
    difficulty: "Medium",
    diffScore: 2,
    grindScore: 4,
    method: "Special",
    location: "Saya's Vision, Earth",
    boss: "Infested Oni",
    missionType: "Defense (Weekly)",
    notes: "Requires completing Saya's Vigil and the main weekly Codex quest. Run Saya's Vision on Earth. Includes pity system with Fate Pearls. Weekly time-gated if relying on pity.",
    blueprint: "Saya's Vision Mission",
    tags: ["defense", "weekly", "dice", "rng-gimmick"],
    wikiUrl: "https://warframe.fandom.com/wiki/Koumei"
  },
  {
    name: "Cyte-09",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Bounty",
    location: "Halcyon Mall, Warframe 1999",
    boss: "N/A",
    missionType: "1999 Bounties + Vendor",
    notes: "Blueprint from The Hex quest. Components from 1999 Bounties and purchasable from Amir (1999 Mall vendor) with 1999 standing. Requires full star chart + Duviri Paradox + Lotus Eaters + The Hex.",
    blueprint: "The Hex Quest",
    tags: ["1999", "the-hex", "gunslinger", "standing-gated"],
    wikiUrl: "https://warframe.fandom.com/wiki/Cyte-09"
  },
  {
    name: "Temple",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Halcyon Mall, Warframe 1999",
    boss: "N/A",
    missionType: "1999 Vendor (Flare)",
    notes: "Parts purchasable from Flare (vendor in Halcyon Mall bar area) with 1999 standing/resources. Requires The Hex quest completion. Also drops from 1999 missions.",
    blueprint: "Flare – Halcyon Mall",
    tags: ["1999", "the-hex", "fire", "exalted"],
    wikiUrl: "https://warframe.fandom.com/wiki/Temple"
  },
  {
    name: "Oraxia",
    difficulty: "Hard",
    diffScore: 3,
    grindScore: 5,
    method: "Special",
    location: "Isle Weaver, Duviri",
    boss: "Oraxia's Lair",
    missionType: "Duviri – Isle Weaver",
    notes: "Farm from Isle Weaver node in Duviri. Requires The Hex quest + Duviri Paradox + Lotus Eaters. Parts drop from missions with pity system via Husk currency from Domino vendor in Drifter Camp.",
    blueprint: "Isle Weaver – Duviri",
    tags: ["duviri", "the-hex", "spider", "invisibility"],
    wikiUrl: "https://warframe.fandom.com/wiki/Oraxia"
  },

  // ─── NIGHTMARE ────────────────────────────────────────────────────────────
  {
    name: "Grendel",
    difficulty: "Nightmare",
    diffScore: 4,
    grindScore: 9,
    method: "Special",
    location: "Europa (Locator missions)",
    boss: "N/A",
    missionType: "No-Mod Missions (3 types)",
    notes: "Blueprint from Market. Parts require Locators (25 Vitus Essence each = 75 total from Arbitration Honors). Then run 3 special Europa missions — Survival, Defense, Excavation — with ALL MODS DISABLED. No Focus, no Operator. Solo/premade only. Enemies Lv 25–30 but your gear feels naked.",
    blueprint: "Market (free)",
    tags: ["arbitration", "no-mods", "hardest"],
    locked: true,
    wikiUrl: "https://warframe.fandom.com/wiki/Grendel"
  }
];

// Compute aggregated stats
const STATS = {
  total: FRAMES.length,
  byDifficulty: FRAMES.reduce((acc, f) => {
    acc[f.difficulty] = (acc[f.difficulty] || 0) + 1;
    return acc;
  }, {})
};

// ═══════════════════════════════════════════════════════════════
// WEAPONS DATA
// ═══════════════════════════════════════════════════════════════
const WEAPONS = [
  // ─── EASY ─────────────────────────────────────────────────────
  { name: "Cronus", type: "Melee", category: "Sword", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Boss", location: "Tolstoj, Mercury", boss: "Captain Vor", missionType: "Assassination", notes: "Blueprint guaranteed from Captain Vor on Mercury. Early game, very fast farm.", blueprint: "Vor drop", locked: false, tags: ["early-game", "sword"], wikiUrl: "https://warframe.fandom.com/wiki/Cronus" },
  { name: "Seer", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Tolstoj, Mercury", boss: "Captain Vor", missionType: "Assassination", notes: "All 3 parts drop from Captain Vor on Mercury. Early and consistent.", blueprint: "Vor drop", locked: false, tags: ["early-game", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Seer" },
  { name: "Twin Gremlins", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Exta, Ceres", boss: "Lech Kril & Capt. Vor", missionType: "Assassination", notes: "Blueprint from Exta boss fight (drop table 2). Blueprint from Market too.", blueprint: "Boss drop / Market", locked: false, tags: ["early-game", "dual-pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Twin_Gremlins" },
  { name: "Miter", type: "Primary", category: "Launcher", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Boss", location: "Exta, Ceres", boss: "Lech Kril & Capt. Vor", missionType: "Assassination", notes: "Parts from Exta (drop table 2). All parts from same boss. Easy farm.", blueprint: "Boss drop", locked: false, tags: ["saw-launcher", "ceres"], wikiUrl: "https://warframe.fandom.com/wiki/Miter" },
  { name: "Boltor", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from the in-game Market for Credits. Very beginner friendly.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "rifle", "beginner"], wikiUrl: "https://warframe.fandom.com/wiki/Boltor" },
  { name: "Braton", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market for Credits. Starter-level rifle.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "rifle", "beginner"], wikiUrl: "https://warframe.fandom.com/wiki/Braton" },
  { name: "Kunai", type: "Secondary", category: "Thrown", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Starter secondary. Also a login reward.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "thrown"], wikiUrl: "https://warframe.fandom.com/wiki/Kunai" },
  { name: "Hek", type: "Primary", category: "Shotgun", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Strong early-to-mid game shotgun.", blueprint: "Market (credits)", locked: false, tags: ["shotgun", "grineer"], wikiUrl: "https://warframe.fandom.com/wiki/Hek" },
  { name: "Karak", type: "Primary", category: "Rifle", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Reliable mid-game Grineer rifle.", blueprint: "Market (credits)", locked: false, tags: ["rifle", "grineer"], wikiUrl: "https://warframe.fandom.com/wiki/Karak" },
  { name: "Orthos", type: "Melee", category: "Polearm", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Great early polearm.", blueprint: "Market (credits)", locked: false, tags: ["polearm", "early-game"], wikiUrl: "https://warframe.fandom.com/wiki/Orthos" },
  { name: "Skana", type: "Melee", category: "Sword", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Starter", location: "Starting loadout", boss: "N/A", missionType: "Starter / Market", notes: "Given as one of the 3 starter weapons. Also available from Market.", blueprint: "Starter / Market", locked: false, tags: ["starter", "sword"], wikiUrl: "https://warframe.fandom.com/wiki/Skana" },

  // ─── MEDIUM ────────────────────────────────────────────────────
  { name: "Pathocyst", type: "Primary", category: "Launcher", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Boss", location: "Exequias, Deimos", boss: "Zealoid Prelate", missionType: "Assassination", notes: "All 3 parts from Zealoid Prelate on Deimos. Unique Infested launcher. Requires Heart of Deimos progress.", blueprint: "Zealoid Prelate drop", locked: false, tags: ["deimos", "infested", "launcher"], wikiUrl: "https://warframe.fandom.com/wiki/Pathocyst" },
  { name: "Broken War", type: "Melee", category: "Sword", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The Second Dream / The War Within", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded from The Second Dream quest. One of the best early swords. Cannot be traded. Lost if sold without The War progression.", blueprint: "Quest reward", locked: true, tags: ["quest-reward", "sword", "shadow-stalker"], wikiUrl: "https://warframe.fandom.com/wiki/Broken_War" },
  { name: "Skiajati", type: "Melee", category: "Nikana", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The Sacrifice Quest", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded from The Sacrifice quest. MR 9+ required. Unique invisibility on finisher. If sold, must redo The Sacrifice which can't be replayed.", blueprint: "The Sacrifice reward", locked: true, tags: ["quest-reward", "nikana", "umbra"], wikiUrl: "https://warframe.fandom.com/wiki/Skiajati" },
  { name: "Paracesis", type: "Melee", category: "Heavy Blade", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Quest", location: "The Sacrifice Quest", boss: "N/A", missionType: "Quest Reward + Crafting", notes: "Blueprint from The Sacrifice. Requires Nitain Extract + Sentient cores. Sentient Anomaly node for Cores. The only weapon that can damage Sentient resistances from the start.", blueprint: "The Sacrifice reward", locked: true, tags: ["quest-reward", "sentient", "heavy-blade"], wikiUrl: "https://warframe.fandom.com/wiki/Paracesis" },
  { name: "Nataruk", type: "Primary", category: "Bow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Quest", location: "The New War Quest", boss: "N/A", missionType: "Quest Reward", notes: "Rewarded at end of The New War quest. Exceptionally powerful bow. Cannot be obtained again from quest — if sold, must buy for plat or trade.", blueprint: "New War quest reward", locked: true, tags: ["quest-reward", "bow", "sentient"], wikiUrl: "https://warframe.fandom.com/wiki/Nataruk" },
  { name: "Cedo", type: "Primary", category: "Shotgun", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Dojo Research", location: "Bio Lab, Clan Dojo", boss: "N/A", missionType: "Dojo Research", notes: "Blueprint from Bio Lab in Clan Dojo. Requires rare Deimos resources for crafting (Thaumica, Mytocardia Spore). One of the best status shotguns.", blueprint: "Bio Lab – Dojo", locked: false, tags: ["dojo", "shotgun", "status"], wikiUrl: "https://warframe.fandom.com/wiki/Cedo" },
  { name: "Zarr", type: "Primary", category: "Launcher", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Dojo Research", location: "Chem Lab, Clan Dojo", boss: "N/A", missionType: "Dojo Research", notes: "Blueprint from Chem Lab in Clan Dojo. Great AoE cannon.", blueprint: "Chem Lab – Dojo", locked: false, tags: ["dojo", "launcher", "aoe"], wikiUrl: "https://warframe.fandom.com/wiki/Zarr" },
  { name: "Ignis Wraith", type: "Primary", category: "Rifle", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Special", location: "Clan Dojo / Trade", boss: "N/A", missionType: "Clan Research / Trading", notes: "Blueprint from a Clan Dojo that researched it during Operation: Tubemen of Regor. Trade with other players if your clan lacks it. Very popular fire weapon.", blueprint: "Clan (event research) / Trade", locked: false, tags: ["clan-event", "flamethrower", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Ignis_Wraith" },
  { name: "Zenith", type: "Primary", category: "Rifle", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 300)", notes: "Rewarded at Day 300 login milestone. Unique alt-fire mode that places auto-target turret. Time-gated by login streak — cannot be obtained any other way.", blueprint: "Day 300 Login Reward", locked: true, tags: ["login-reward", "unique", "time-gated"], wikiUrl: "https://warframe.fandom.com/wiki/Zenith" },
  { name: "Stug", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Corpus blob pistol. Blueprint from Market.", blueprint: "Market (credits)", locked: false, tags: ["corpus", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Stug" },
  { name: "Furis", type: "Secondary", category: "Pistol", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. The auto-pistol you get with Warframe starter pack.", blueprint: "Market (credits)", locked: false, tags: ["early-game", "pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Furis" },
  { name: "Arca Plasmor", type: "Primary", category: "Shotgun", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Syndicate", location: "Arbiters of Hexis / Red Veil", boss: "N/A", missionType: "Syndicate Offering", notes: "Bought from Arbiters of Hexis or Red Veil syndicate at max rank for 20,000 standing. Requires Rank 5 (Exalted).", blueprint: "Syndicate offering", locked: false, tags: ["syndicate", "shotgun", "void-damage"], wikiUrl: "https://warframe.fandom.com/wiki/Arca_Plasmor" },
  { name: "Catchmoon", type: "Secondary", category: "Kitgun", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna / Cetus", boss: "N/A", missionType: "Kitgun Crafting", notes: "Assembled from Kitgun parts: Catchmoon chamber + any grip + any loader. Buy parts from Legs in Fortuna. Requires Solaris United standing.", blueprint: "Legs – Fortuna (Kitgun parts)", locked: false, tags: ["kitgun", "fortuna", "secondary"], wikiUrl: "https://warframe.fandom.com/wiki/Catchmoon" },
  { name: "Glaive", type: "Melee", category: "Glaive", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Blueprint from Market. Iconic thrown melee disc. Good utility on Glaive-type builds.", blueprint: "Market (credits)", locked: false, tags: ["glaive", "thrown"], wikiUrl: "https://warframe.fandom.com/wiki/Glaive" },
  { name: "Redeemer", type: "Melee", category: "Gunblade", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase", notes: "Gunblade blueprint from Market. Unique combo mechanic.", blueprint: "Market (credits)", locked: false, tags: ["gunblade", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Redeemer" },

  // ─── HARD ──────────────────────────────────────────────────────
  { name: "Kuva Bramma", type: "Primary", category: "Bow", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Random chance to spawn from Kuva Lich. Farm murmurs across Grineer missions. Need to complete The War Within first. RNG on weapon type per Lich.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "bow", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Bramma" },
  { name: "Kuva Nukor", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Random type per Lich spawn. Extremely powerful secondary — Kuva Nukor variant is top meta. Complete The War Within first. Farm murmurs on Grineer nodes.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "pistol", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Nukor" },
  { name: "Kuva Zarr", type: "Primary", category: "Launcher", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Kuva Lich System", boss: "Kuva Lich", missionType: "Nemesis (Kuva Lich)", notes: "Spawn a Lich wielding Zarr via Grineer missions. High AoE damage. Requires War Within + murmur grind.", blueprint: "Kuva Lich vanquish/convert", locked: false, tags: ["kuva", "nemesis", "launcher", "aoe"], wikiUrl: "https://warframe.fandom.com/wiki/Kuva_Zarr" },
  { name: "Tenet Arca Plasmor", type: "Primary", category: "Shotgun", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Sister of Parvos System", boss: "Sister of Parvos", missionType: "Nemesis (Sister)", notes: "Random Sister weapon type. Requires Call of the Tempestarii quest + Granum Void entry. Strong Void-damage shotgun variant.", blueprint: "Sister of Parvos vanquish/convert", locked: false, tags: ["tenet", "nemesis", "shotgun", "void-damage"], wikiUrl: "https://warframe.fandom.com/wiki/Tenet_Arca_Plasmor" },
  { name: "Tenet Cycron", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 7, method: "Special", location: "Sister of Parvos System", boss: "Sister of Parvos", missionType: "Nemesis (Sister)", notes: "Random Sister weapon. Requires Call of the Tempestarii + Granum Void. Powerful beam pistol with viral.", blueprint: "Sister of Parvos vanquish/convert", locked: false, tags: ["tenet", "nemesis", "beam-pistol"], wikiUrl: "https://warframe.fandom.com/wiki/Tenet_Cycron" },
  { name: "Felarx", type: "Primary", category: "Shotgun", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", notes: "Requires Duviri Paradox quest completion then farming Incarnon Genesis adapter via The Circuit (Steel Path). Weekly gated by Circuit rotations.", boss: "N/A", missionType: "Duviri Circuit (Weekly)", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "shotgun", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Felarx" },
  { name: "Phenmor", type: "Primary", category: "Rifle", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", boss: "N/A", missionType: "Duviri Circuit (Weekly)", notes: "Incarnon weapon from Duviri Circuit. Weekly-gated rotations. Need Duviri Paradox completed.", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "rifle", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Phenmor" },
  { name: "Laetum", type: "Secondary", category: "Pistol", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Duviri – The Circuit", boss: "N/A", missionType: "Duviri Circuit (Weekly)", notes: "Top-tier Incarnon pistol. Duviri Circuit weekly. Requires Duviri Paradox completion.", blueprint: "Duviri Circuit – Incarnon Genesis", locked: false, tags: ["incarnon", "duviri", "pistol", "meta", "weekly"], wikiUrl: "https://warframe.fandom.com/wiki/Laetum" },
  { name: "Praedos", type: "Melee", category: "Tonfas", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Duviri – Acrithis Shop", boss: "N/A", missionType: "Duviri", notes: "Buy blueprint from Acrithis in Duviri using Pathos Clamps and Duviri resources. No RNG but requires running Duviri content.", blueprint: "Acrithis – Duviri", locked: false, tags: ["duviri", "tonfas"], wikiUrl: "https://warframe.fandom.com/wiki/Praedos" },
  { name: "Verdilac", type: "Melee", category: "Whip", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Duviri – Acrithis Shop", boss: "N/A", missionType: "Duviri", notes: "Buy from Acrithis in Duviri with Pathos Clamps.", blueprint: "Acrithis – Duviri", locked: false, tags: ["duviri", "whip"], wikiUrl: "https://warframe.fandom.com/wiki/Verdilac" },
  { name: "Sporothrix", type: "Primary", category: "Sniper", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "Son – Token system", missionType: "Token Vendor", notes: "Buy from Son in Necralisk with Son Tokens earned from conservation (Deimos animals). Requires grinding Son standing + tokens.", blueprint: "Son – Necralisk (tokens)", locked: false, tags: ["deimos", "conservation", "sniper"], wikiUrl: "https://warframe.fandom.com/wiki/Sporothrix" },
  { name: "Bubonico", type: "Primary", category: "Launcher", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "Son – Token system", missionType: "Token Vendor", notes: "Son Token vendor in Necralisk. Conservation + Deimos standing required.", blueprint: "Son – Necralisk (tokens)", locked: false, tags: ["deimos", "conservation", "launcher"], wikiUrl: "https://warframe.fandom.com/wiki/Bubonico" },
  { name: "Cortege", type: "Primary", category: "Rifle", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Bounty", location: "Zariman / Holdfasts", boss: "N/A", missionType: "Holdfasts Bounty", notes: "Parts from Holdfasts bounties on Zariman. Requires Angels of the Zariman quest.", blueprint: "Holdfasts Bounty – Zariman", locked: false, tags: ["zariman", "bounty", "void"], wikiUrl: "https://warframe.fandom.com/wiki/Cortege" },
  { name: "Gaze", type: "Secondary", category: "Kitgun", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna", boss: "N/A", missionType: "Kitgun Crafting", notes: "Gaze chamber Kitgun. Buy from Legs in Fortuna with Solaris United standing.", blueprint: "Legs – Fortuna (Kitgun parts)", locked: false, tags: ["kitgun", "fortuna", "beam"], wikiUrl: "https://warframe.fandom.com/wiki/Gaze" },

  // ─── NIGHTMARE ─────────────────────────────────────────────────
  { name: "Mutalist Quanta", type: "Primary", category: "Rifle", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Eris Invasion Alerts", boss: "N/A", missionType: "Invasion (Infested)", notes: "Blueprint ONLY from specific Infested Invasion alerts. Appears rarely. You must watch the Alerts tab. If you miss it, wait for the next rotation. Very time-gated.", blueprint: "Invasion Alert (Infested)", locked: true, tags: ["alert-only", "invasion", "time-gated", "rare"], wikiUrl: "https://warframe.fandom.com/wiki/Mutalist_Quanta" },
  { name: "Prisma Gorgon", type: "Primary", category: "Rifle", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Baro Ki'Teer (Void Trader)", boss: "N/A", missionType: "Void Trader (Bi-weekly)", notes: "ONLY sold by Baro Ki'Teer when he visits a Relay every 2 weeks. Costs Ducats + Credits. Very limited availability — miss the window and wait 2 more weeks.", blueprint: "Baro Ki'Teer (Ducats + Credits)", locked: true, tags: ["baro", "void-trader", "time-gated", "ducats"], wikiUrl: "https://warframe.fandom.com/wiki/Prisma_Gorgon" },
  { name: "Prisma Skana", type: "Melee", category: "Sword", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Baro Ki'Teer (Void Trader)", boss: "N/A", missionType: "Void Trader (Bi-weekly)", notes: "Only from Baro Ki'Teer during his visits. Limited Ducats + Credits cost. Rotates irregularly — can be months between appearances.", blueprint: "Baro Ki'Teer", locked: true, tags: ["baro", "void-trader", "time-gated"], wikiUrl: "https://warframe.fandom.com/wiki/Prisma_Skana" },
  { name: "Azima", type: "Secondary", category: "Pistol", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 100)", notes: "Rewarded only at Day 100 of login milestones. Cannot be earned any other way without trading. If sold, must trade or wait years for another login cycle.", blueprint: "Day 100 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Azima" },
  { name: "Zylok", type: "Secondary", category: "Pistol", difficulty: "Nightmare", diffScore: 4, grindScore: 8, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 200)", notes: "Rewarded only at Day 200 login milestone. No other acquisition method.", blueprint: "Day 200 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Zylok" },
  { name: "Sigma & Octantis", type: "Melee", category: "Sword & Shield", difficulty: "Nightmare", diffScore: 4, grindScore: 9, method: "Special", location: "Daily Login Reward", boss: "N/A", missionType: "Login Reward (Day 600)", notes: "Day 600 login milestone ONLY. The longest grind for any weapon in the game if playing daily.", blueprint: "Day 600 Login Reward", locked: true, tags: ["login-reward", "time-gated", "unique", "endgame"], wikiUrl: "https://warframe.fandom.com/wiki/Sigma_%26_Octantis" },
];

// ═══════════════════════════════════════════════════════════════
// COMPANIONS DATA
// ═══════════════════════════════════════════════════════════════
const COMPANIONS = [
  // ─── SENTINELS ─────────────────────────────────────────────────
  { name: "Taxon", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 1, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market for Credits. Very first companion most players get. Comes with Molecular Conversion (shield restore on damage).", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "beginner", "shield"], wikiUrl: "https://warframe.fandom.com/wiki/Taxon" },
  { name: "Carrier", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Most popular sentinel for its Vacuum (auto-loot) and Ammo Case mods. Essential for most builds.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "vacuum", "meta", "ammo"], wikiUrl: "https://warframe.fandom.com/wiki/Carrier" },
  { name: "Shade", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Ghost precept cloaks you when enemies are near — great for stealth builds.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "stealth", "cloak"], wikiUrl: "https://warframe.fandom.com/wiki/Shade" },
  { name: "Wyrm", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Negate mod blocks a status proc every 5 seconds. Crowd Control via Crowd Dispersion.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "status-resist", "cc"], wikiUrl: "https://warframe.fandom.com/wiki/Wyrm" },
  { name: "Dethcube", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Energy Generator mod drops energy orbs — useful for energy management.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "energy", "dps"], wikiUrl: "https://warframe.fandom.com/wiki/Dethcube" },
  { name: "Helios", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Auto-scans enemies to fill Codex. Investigator precept unique. Synergizes with Synthesis Scanner.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "codex", "scanner"], wikiUrl: "https://warframe.fandom.com/wiki/Helios" },
  { name: "Diriga", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Electric-type sentinel. Arc Coil chains electricity to nearby enemies.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "electric", "aoe"], wikiUrl: "https://warframe.fandom.com/wiki/Diriga" },
  { name: "Djinn", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Fatal Attraction pulls enemies in. Self-revives after death via Reawaken mod.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "pull", "self-revive"], wikiUrl: "https://warframe.fandom.com/wiki/Djinn" },
  { name: "Oxylus", type: "Sentinel", difficulty: "Easy", diffScore: 1, grindScore: 2, method: "Market", location: "In-game Market", boss: "N/A", missionType: "Purchase (Credits)", notes: "Blueprint from Market. Scan Lifeforms mod auto-marks conservation animals on minimap. Essential for conservation/hunting.", blueprint: "Market (credits)", locked: false, tags: ["sentinel", "conservation", "fishing"], wikiUrl: "https://warframe.fandom.com/wiki/Oxylus" },
  { name: "Nautilus", type: "Sentinel", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Special", location: "Railjack (Dry Dock)", boss: "N/A", missionType: "Railjack Crafting", notes: "Blueprint from Railjack (Dry Dock research). Cordon precept groups enemies. Auto Omni repairs Railjack hull. Requires Railjack content unlocked.", blueprint: "Dry Dock – Railjack", locked: false, tags: ["sentinel", "railjack", "grouping"], wikiUrl: "https://warframe.fandom.com/wiki/Nautilus" },

  // ─── KUBROWS ─────────────────────────────────────────────────
  { name: "Huras Kubrow", type: "Kubrow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Kubrow Den, Earth", boss: "N/A", missionType: "Breeding (Incubator)", notes: "Find Kubrow Egg in Earth forest missions (destroy dens). 50/50 random breed. Need Incubator Power Core. Complete Howl of the Kubrow quest first.", blueprint: "Incubator + Kubrow Egg", locked: false, tags: ["kubrow", "stealth", "cloaking"], wikiUrl: "https://warframe.fandom.com/wiki/Huras_Kubrow" },
  { name: "Sahasa Kubrow", type: "Kubrow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Kubrow Den, Earth", boss: "N/A", missionType: "Breeding (Incubator)", notes: "Random breed from Kubrow Egg. Use imprints of Sahasa to guarantee breed. Dig precept finds loot from dead enemies.", blueprint: "Incubator + Kubrow Egg", locked: false, tags: ["kubrow", "loot", "dig"], wikiUrl: "https://warframe.fandom.com/wiki/Sahasa_Kubrow" },
  { name: "Raksa Kubrow", type: "Kubrow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Kubrow Den, Earth", boss: "N/A", missionType: "Breeding (Incubator)", notes: "Random breed from Kubrow Egg. Howl mod restores shields and alerts the pack. Great defensive companion.", blueprint: "Incubator + Kubrow Egg", locked: false, tags: ["kubrow", "shield", "defense"], wikiUrl: "https://warframe.fandom.com/wiki/Raksa_Kubrow" },
  { name: "Sunika Kubrow", type: "Kubrow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Kubrow Den, Earth", boss: "N/A", missionType: "Breeding (Incubator)", notes: "Random breed. Savagery precept strips enemies of abilities. Violate precept for capture targets.", blueprint: "Incubator + Kubrow Egg", locked: false, tags: ["kubrow", "cc", "capture"], wikiUrl: "https://warframe.fandom.com/wiki/Sunika_Kubrow" },
  { name: "Chesa Kubrow", type: "Kubrow", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Kubrow Den, Earth", boss: "N/A", missionType: "Breeding (Incubator)", notes: "Random breed or use imprints. Retrieve precept collects loot from nearby corpses — great for resource farming.", blueprint: "Incubator + Kubrow Egg", locked: false, tags: ["kubrow", "loot-frame", "retrieve"], wikiUrl: "https://warframe.fandom.com/wiki/Chesa_Kubrow" },
  { name: "Helminth Charger", type: "Kubrow", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Helminth Infirmary", boss: "N/A", missionType: "Helminth Nidus Feeding", notes: "Only spawned via the Helminth Infirmary using Nidus' strains. Requires unlocking Helminth system AND having Nidus. Infested dog with powerful Proboscis ability.", blueprint: "Helminth Infirmary (Nidus required)", locked: false, tags: ["kubrow", "infested", "nidus", "helminth"], wikiUrl: "https://warframe.fandom.com/wiki/Helminth_Charger" },

  // ─── KAVATS ──────────────────────────────────────────────────
  { name: "Smeeta Kavat", type: "Kavat", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Special", location: "Orokin Derelict, Deimos", boss: "Feral Kavats", missionType: "Scanning + Breeding", notes: "Scan Feral Kavats on Deimos (Horend, Phlegyas, Formido) for 10 Genetic Codes (1.5% each). Random 50/50 breed. Need Kavat Incubator Upgrade Segment from Tenno Lab or Hyekka Master drop.", blueprint: "Genetic Codes + Incubator", locked: false, tags: ["kavat", "luck", "meta", "charm"], wikiUrl: "https://warframe.fandom.com/wiki/Smeeta_Kavat" },
  { name: "Adarza Kavat", type: "Kavat", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Special", location: "Orokin Derelict, Deimos", boss: "Feral Kavats", missionType: "Scanning + Breeding", notes: "Same breeding as Smeeta. Random 50/50 breed. Reflect mod buffs crit chance for squad members. Great for crit builds.", blueprint: "Genetic Codes + Incubator", locked: false, tags: ["kavat", "crit", "buff", "support"], wikiUrl: "https://warframe.fandom.com/wiki/Adarza_Kavat" },
  { name: "Vasca Kavat", type: "Kavat", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Plains of Eidolon (Night)", boss: "Vasca Kavat (feral)", missionType: "Breeding (Imprints required)", notes: "Get an existing Kavat infected by a Vasca on PoE at night, then make imprints. Requires 2 Vasca imprints. Cannot get Vasca type any other way. Health-based abilities.", blueprint: "Vasca infection + 2 imprints", locked: false, tags: ["kavat", "poe", "health-regen", "unique"], wikiUrl: "https://warframe.fandom.com/wiki/Vasca_Kavat" },

  // ─── MOAs ────────────────────────────────────────────────────
  { name: "Para MOA", type: "MOA", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna (Legs)", boss: "N/A", missionType: "Modular Crafting", notes: "Assemble from MOA parts (Model, Core, Gyro, Bracket). Buy parts from Legs in Fortuna with Solaris United standing. Customizable precepts.", blueprint: "Legs – Fortuna (MOA parts)", locked: false, tags: ["moa", "fortuna", "modular"], wikiUrl: "https://warframe.fandom.com/wiki/MOA_(Companion)" },
  { name: "Oloro MOA", type: "MOA", difficulty: "Medium", diffScore: 2, grindScore: 3, method: "Special", location: "Fortuna (Legs)", boss: "N/A", missionType: "Modular Crafting", notes: "Modular MOA from Legs. Higher rank Solaris United unlocks better parts. Support-focused MOA variant.", blueprint: "Legs – Fortuna (MOA parts)", locked: false, tags: ["moa", "fortuna", "support"], wikiUrl: "https://warframe.fandom.com/wiki/MOA_(Companion)" },

  // ─── HOUNDS ──────────────────────────────────────────────────
  { name: "Custom Hound", type: "Hound", difficulty: "Hard", diffScore: 3, grindScore: 6, method: "Special", location: "Sister of Parvos / Legs (Fortuna)", boss: "Sister of Parvos", missionType: "Nemesis System", notes: "Defeat a Sister of Parvos to receive a fully-built random Hound + 1 random part blueprint. Then build custom Hounds via Legs with standing. Requires Call of the Tempestarii quest.", blueprint: "Sister of Parvos drop + Legs", locked: false, tags: ["hound", "sister", "modular", "corpus"], wikiUrl: "https://warframe.fandom.com/wiki/Hound_(Companion)" },

  // ─── OPEN WORLD PETS ─────────────────────────────────────────
  { name: "Sly Vulpaphyla", type: "Vulpaphyla", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Acquire via Son Token conservation system on Deimos. Sly variant grants Camo precept (invisibility when idle). Need to do Deimos conservation with Son Tokens.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["vulpaphyla", "deimos", "stealth", "fox"], wikiUrl: "https://warframe.fandom.com/wiki/Sly_Vulpaphyla" },
  { name: "Panzer Vulpaphyla", type: "Vulpaphyla", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Most popular Vulpaphyla. Viral Quills precept spreads Viral status — excellent for status builds. Same Son Token/conservation method.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["vulpaphyla", "deimos", "viral", "meta", "fox"], wikiUrl: "https://warframe.fandom.com/wiki/Panzer_Vulpaphyla" },
  { name: "Crescent Vulpaphyla", type: "Vulpaphyla", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Conservation tokens from Son. Pack Leader mod heals self from melee kills. Defensive variant.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["vulpaphyla", "deimos", "healing", "fox"], wikiUrl: "https://warframe.fandom.com/wiki/Crescent_Vulpaphyla" },
  { name: "Vizier Predasite", type: "Predasite", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Same Son conservation system. Predasites are Infested cat-like companions. Vizier has Medi-Pet Kit equivalent.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["predasite", "deimos", "healing", "infested"], wikiUrl: "https://warframe.fandom.com/wiki/Vizier_Predasite" },
  { name: "Medjay Predasite", type: "Predasite", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Conservation tokens from Son on Deimos. Tenacious Bond mod boosts weapon stats. Strong for damage builds.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["predasite", "deimos", "damage-buff", "infested"], wikiUrl: "https://warframe.fandom.com/wiki/Medjay_Predasite" },
  { name: "Pharaoh Predasite", type: "Predasite", difficulty: "Hard", diffScore: 3, grindScore: 5, method: "Special", location: "Cambion Drift, Deimos", boss: "N/A", missionType: "Conservation + Son Tokens", notes: "Conservation tokens from Son. Scan precept helps fill Codex. Great for Synthesis Scanner users.", blueprint: "Son – Necralisk (conservation tokens)", locked: false, tags: ["predasite", "deimos", "scan", "infested"], wikiUrl: "https://warframe.fandom.com/wiki/Pharaoh_Predasite" },

  // ─── PRIMES (HARDER) ─────────────────────────────────────────
  { name: "Carrier Prime", type: "Sentinel", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Void Relic", location: "Void Fissure Missions", boss: "N/A", missionType: "Void Relics", notes: "Prime parts from Void Relics. Run Void Fissure missions with appropriate relics. Carrier Prime = best Vacuum + stat upgrade over base Carrier.", blueprint: "Void Relics", locked: false, tags: ["sentinel", "prime", "void-relic", "vacuum", "meta"], wikiUrl: "https://warframe.fandom.com/wiki/Carrier_Prime" },
  { name: "Wyrm Prime", type: "Sentinel", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Void Relic", location: "Void Fissure Missions", boss: "N/A", missionType: "Void Relics", notes: "Prime parts from Void Relics. Negate + Crowd Dispersion combo great for status resistance.", blueprint: "Void Relics", locked: false, tags: ["sentinel", "prime", "void-relic", "cc"], wikiUrl: "https://warframe.fandom.com/wiki/Wyrm_Prime" },
  { name: "Helios Prime", type: "Sentinel", difficulty: "Medium", diffScore: 2, grindScore: 4, method: "Void Relic", location: "Void Fissure Missions", boss: "N/A", missionType: "Void Relics", notes: "Prime version from Void Relics. Better stats than base Helios. Still auto-scans for Codex.", blueprint: "Void Relics", locked: false, tags: ["sentinel", "prime", "void-relic", "codex"], wikiUrl: "https://warframe.fandom.com/wiki/Helios_Prime" },
];
